### PR TITLE
Add macOS support. Should work on both Intel and Silicon Macs.

### PR DESCRIPTION
**Pull request by TheBloke**
Support for macOS. Should work with both Intel and Silicon Macs.

### CODE REVIEW

**Comment by marella** [comment]
Thanks

**Comment by marella** [comment]
Hi, I found that I was creating unoptimized builds for Windows. Basically I was using `cmake --build .` instead of `cmake --build . --config Release`. I just updated the steps on [README](https://github.com/marella/gptj.cpp#build).
Can you please check if similar issue is present on macOS and kindly send a PR if the files have changed after using `cmake --build . --config Release` command.
Thanks.

**Comment by TheBloke** [comment]
OK I tried that, but it makes no difference.

```
tomj@Eddie ~/src/gptj.cpp/build (main●)$ cmake --build . --config Release
[ 25%] Building C object ggml/src/CMakeFiles/ggml.dir/ggml.c.o
[ 50%] Linking C shared library libggml.dylib
[ 50%] Built target ggml
[ 75%] Building CXX object src/CMakeFiles/gptj.dir/gptj.cpp.o
/Users/tomj/src/gptj.cpp/src/gptj.cpp:48:30: warning: 'gpt_tokenize' has C-linkage specified, but returns user-defined type 'std::vector<gpt_vocab::id>' (aka 'vector<int>') which is incompatible with C [-Wreturn-type-c-linkage]
  std::vector<gpt_vocab::id> gpt_tokenize(const gpt_vocab &vocab, const std::string &text)
                             ^
1 warning generated.
/Users/tomj/src/gptj.cpp/src/gptj.cpp:48:30: warning: 'gpt_tokenize' has C-linkage specified, but returns user-defined type 'std::vector<gpt_vocab::id>' (aka 'vector<int>') which is incompatible with C [-Wreturn-type-c-linkage]
  std::vector<gpt_vocab::id> gpt_tokenize(const gpt_vocab &vocab, const std::string &text)
                             ^
1 warning generated.
[100%] Linking CXX shared library libgptj.dylib
[100%] Built target gptj

tomj@Eddie ~/src/gptj.cpp/build (main●)$ cd ..

tomj@Eddie ~/src/gptj.cpp (main●)$ ls -al build.orig/src/libgptj.dylib build/src/libgptj.dylib
-rwxr-xr-x  1 tomj  staff  365898 17 Apr 22:30 build.orig/src/libgptj.dylib
-rwxr-xr-x  1 tomj  staff  365898 18 Apr 17:32 build/src/libgptj.dylib
tomj@Eddie ~/src/gptj.cpp (main●)$ ls -al build.orig/ggml/src/libggml.dylib build/ggml/src/libggml.dylib
-rwxr-xr-x  1 tomj  staff  400954 17 Apr 22:30 build.orig/ggml/src/libggml.dylib
-rwxr-xr-x  1 tomj  staff  400954 18 Apr 17:32 build/ggml/src/libggml.dylib

tomj@Eddie ~/src/gptj.cpp (main●)$ cmp build.orig/ggml/src/libggml.dylib build/ggml/src/libggml.dylib
tomj@Eddie ~/src/gptj.cpp (main●)$ cmp build.orig/src/libgptj.dylib build/src/libgptj.dylib
tomj@Eddie ~/src/gptj.cpp (main●)$
```

So no need for new PR.

**Comment by marella** [comment]
Thanks for checking.

**Comment by marella** [comment]
Hi, I automated the build process using GitHub Actions. Currently they are located here: https://github.com/marella/gptj.cpp/tree/main/lib
Can you please check if the newly generated files are working for you on macOS by downloading them from above link and using them as:

```py
from gpt4allj import Model, load_library

lib = load_library('/path/to/gptj.cpp/lib/libgptj.dylib', '/path/to/gptj.cpp/lib/libggml.dylib')

model = Model('...', lib=lib)
```

**Comment by TheBloke** [comment]
Works fine! Great work, thanks
```
tomj@Eddie ~/src/gpt4all-j (main)$ python
Python 3.11.3 (main, Apr  7 2023, 19:25:52) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from gpt4allj import Model, load_library
>>> lib = load_library('/Users/tomj/src/gpt4all-j/gpt4allj/lib/libgptj.dylib', '/Users/tomj/src/gpt4all-j/gpt4allj/lib/libggml.dylib')
>>> model = Model('/Volumes/EVOB/models/gpt-j/ggml-gpt4all-j-v1.2-jazzy.bin', lib=lib)
gptj_model_load: loading model from '/Volumes/EVOB/models/gpt-j/ggml-gpt4all-j-v1.2-jazzy.bin' - please wait ...
gptj_model_load: n_vocab = 50400
gptj_model_load: n_ctx   = 2048
gptj_model_load: n_embd  = 4096
gptj_model_load: n_head  = 16
gptj_model_load: n_layer = 28
gptj_model_load: n_rot   = 64
gptj_model_load: f16     = 2
gptj_model_load: ggml ctx size = 5401.45 MB
gptj_model_load: memory_size =  1792.00 MB, n_mem = 57344
gptj_model_load: ................................... done
gptj_model_load: model size =  3609.38 MB / num tensors = 285
>>> model.generate("Homer Simpson is ")
gptj_generate: seed = 1682087957
gptj_generate: number of tokens in prompt = 5

Homer Simpson is
The main protagonist of the novel Home Sweet Home by L.M. Montgomery.
```

**Comment by marella** [comment]
Thanks for checking but it looks like you are checking the old libs from gpt4all-j repo. The new libs are located in gptj.cpp repo here: https://github.com/marella/gptj.cpp/tree/main/lib
I haven't yet copied them to the gpt4all-j repo.

**Comment by marella** [comment]
Thanks for the detailed explanation. When I tested on Windows and Linux, I didn't notice a performance drop.
I will read upon this further and will ask you if I need any help. I will also see how gpt4all-chat is handling it. Thanks.

**Comment by marella** [comment]
You are correct, the CPU used in macOS runners doesn't support AVX2 (it only supports AVX).
So I built the libs by forcing the `-mfma -mavx2` flags on macOS and saved them here: https://github.com/marella/test-cmake-202304/tree/76efeead185ad0bf3f0d7ec49daaa295674b3977/lib (please note that the files are in a different temporary repo created for testing)
Can you please check if above files are working and have similar performance to the files you built.

**Comment by marella** [comment]
I added separate precompiled libs for AVX and AVX2 for all OSes in the latest version 0.2.0 and I gave an option for users to select AVX if AVX2 doesn't work for them:

```py
model = Model('...', instructions='avx')
```

**Comment by TheBloke** [comment]
Firstly, so sorry not to reply to your earlier message. It came when I was busy then I forgot to go back to it.

That's great news re the libs and that sounds like a good idea.

I ran a quick test using v0.2.1's bundled libs vs self compiled libs and the performance was identical. So all looks good!

**Comment by marella** [comment]
Hey no worries. Thanks for checking.
Good to know that the performance is identical.

**Pull request merged**
